# Generated by Django 2.0.5 on 2018-05-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_divipola_colombia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrospoblados',
            options={'ordering': ['codigo'], 'verbose_name': 'CentroPoblado', 'verbose_name_plural': 'Centros Poblados'},
        ),
        migrations.AlterModelOptions(
            name='departamentos',
            options={'ordering': ['codigo'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='municipios',
            options={'ordering': ['codigo'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
    ]
